### ISSUE TITLE
Dealing with "exceptions"

### ISSUE THREAD

**Issue by jeznag** [raisely/jwl#18]
Let's say there's an organisation like Engie which currently runs coal power stations but is actively moving towards 100% renewables. They might want to use software licensed under JWL but have concerns that they would violate clause 4b. How do we deal with that? Would they raise an issue here asking if they're allowed to use it?

Some of the clauses are a bit grey (particularly 4b) in my opinion and would therefore prompt these kind of questions.

**Comment by chrisjensen** [comment]
We don't have the resources to be an administrative body for such things and also it wouldn't really make sense.

Software licenses are expected to be static documents. If they can change after the software is released, it makes it harder for people to adopt the software as they may fear that the license may change in unexpected ways.

The more appropriate channel would be for the company to apply to the author of the software to ask them to license it to them under different conditions (as [IBM did with JSLint](https://wonko.com/post/jsmin-isnt-welcome-on-google-code))
